[variables]
ASPNETCORE_ENVIRONMENT = 'Production'
ASPNETCORE_URLS = 'http://0.0.0.0:3000'
DOTNET_ROOT = '/nix/var/nix/profiles/default/'

[phase.name]
nixpkgsArchive = "a45fa362d887f4d4a7157d95c28ca9ce2899b70e"


[phases.build]
dependsOn = ['install']
cmds = [
    'dotnet publish ./Rasputin-Server/Rasputin-Server.csproj --no-restore -c Release -o ./out/server',
    'dotnet publish ./Rasputin-MessageQueue-Consumer/Rasputin-MessageQueue-Consumer.csproj --no-restore -c Release -o ./out/consumer',
    'dotnet publish ./Rasputin-Jobs/Rasputin-Jobs.csproj --no-restore -c Release -o ./out/jobs'
]

[phases.install]
dependsOn = ['setup']
cmds = ['dotnet restore']

[phases.setup]
nixPkgs = ['dotnet-sdk']
nixOverlays = []
nixpkgsArchive = "a45fa362d887f4d4a7157d95c28ca9ce2899b70e"

[start]
cmd = 'dotnet ./out/server/Rasputin-Server.dll' 