// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("clan_members")]
[Index("GroupId", "GroupRole", "MembershipId", IsUnique = true)]
[Index("GroupId", "GroupRole", Name = "clan_members_group_id_group_role_index")]
[Index("GroupId", Name = "clan_members_group_id_index")]
[Index("GroupRole", Name = "clan_members_group_role_index")]
[Index("JoinedAt", Name = "clan_members_joined_at_index")]
[Index("MembershipId", Name = "clan_members_membership_id_index")]
public partial class ClanMember
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("group_id")]
    public long GroupId { get; set; }

    [Column("group_role")]
    public int GroupRole { get; set; }

    [Column("membership_id")]
    public long MembershipId { get; set; }

    [Column("platform")]
    public int Platform { get; set; }

    [Column("joined_at")]
    public long JoinedAt { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}