// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("clans")]
[Index("GroupId", IsUnique = true)]
[Index("GroupId", Name = "clans_group_id_index")]
[Index("IsNetwork", Name = "clans_is_network_index")]
[Index("Name", Name = "clans_name_index")]
[Index("Slug", Name = "clans_slug_index")]
public partial class Clan
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("group_id")]
    public long GroupId { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("slug")]
    public string Slug { get; set; }

    [Column("is_network")]
    public bool IsNetwork { get; set; }

    [Required]
    [Column("motto")]
    public string Motto { get; set; }

    [Required]
    [Column("about")]
    public string About { get; set; }

    [Required]
    [Column("call_sign")]
    public string CallSign { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}