// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

public partial class DBDestinyContext : DbContext
{
    public DBDestinyContext(DbContextOptions<DBDestinyContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Clan> Clans { get; set; }

    public virtual DbSet<ClanMember> ClanMembers { get; set; }

    public virtual DbSet<Instance> Instances { get; set; }

    public virtual DbSet<InstanceMember> InstanceMembers { get; set; }

    public virtual DbSet<ManifestActivity> ManifestActivities { get; set; }

    public virtual DbSet<ManifestActivityType> ManifestActivityTypes { get; set; }

    public virtual DbSet<ManifestClass> ManifestClasses { get; set; }

    public virtual DbSet<ManifestSeason> ManifestSeasons { get; set; }

    public virtual DbSet<ManifestTriumph> ManifestTriumphs { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<MemberActivity> MemberActivities { get; set; }

    public virtual DbSet<MemberActivityStat> MemberActivityStats { get; set; }

    public virtual DbSet<MemberCharacter> MemberCharacters { get; set; }

    //public virtual DbSet<MemberSnapshot> MemberSnapshots { get; set; }

    public virtual DbSet<MemberTriumph> MemberTriumphs { get; set; }

  //  public virtual DbSet<SettingMode> SettingModes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}