// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using MySqlConnector;

namespace Rasputin.Database.Models;

public partial class DBDestinyContext : DbContext
{
    private RasputinDatabaseConfig _config;
    
    public DBDestinyContext()
    {
        _config = RasputinDatabaseConfig.Load();
    }
    
    public DBDestinyContext(DbContextOptions<DBDestinyContext> options)
        : base(options)
    {
        _config = RasputinDatabaseConfig.Load();
    }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (!optionsBuilder.IsConfigured)
        {
            if (_config.Type == "MySql")
            {
                var builder = new MySqlConnectionStringBuilder();
                builder.Server = _config.Host;
                builder.Database = _config.Database;
                builder.UserID = _config.Username;
                builder.Password = _config.Password;
                builder.Port = _config.Port;
                var connectionString = builder.ToString();
                optionsBuilder.UseMySql(connectionString, ServerVersion.AutoDetect(connectionString));
            }
            else
            {
                /*
                var connectionStringBuilder = new SqliteConnectionStringBuilder(_config.Database + ".db");
                connectionStringBuilder.DataSource = Path.Combine(AppDomain.CurrentDomain.BaseDirectory,
                    connectionStringBuilder.DataSource);
                optionsBuilder.UseSqlite(connectionStringBuilder.ToString()); */
            }
        }
    }
        
    public virtual DbSet<Clan> Clans { get; set; }

    public virtual DbSet<ClanMember> ClanMembers { get; set; }

    public virtual DbSet<Instance> Instances { get; set; }

    public virtual DbSet<InstanceMember> InstanceMembers { get; set; }

    public virtual DbSet<ManifestActivity> ManifestActivities { get; set; }

    public virtual DbSet<ManifestActivityType> ManifestActivityTypes { get; set; }

    public virtual DbSet<ManifestClass> ManifestClasses { get; set; }

    public virtual DbSet<ManifestSeason> ManifestSeasons { get; set; }

    public virtual DbSet<ManifestTriumph> ManifestTriumphs { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<MemberActivity> MemberActivities { get; set; }

    public virtual DbSet<MemberActivityStat> MemberActivityStats { get; set; }

    public virtual DbSet<MemberCharacter> MemberCharacters { get; set; }

    //public virtual DbSet<MemberSnapshot> MemberSnapshots { get; set; }

    public virtual DbSet<MemberTriumph> MemberTriumphs { get; set; }

  //  public virtual DbSet<SettingMode> SettingModes { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}