// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("instances")]
[Index("InstanceId", IsUnique = true)]
[Index("ActivityDirectorHash", Name = "instances_activity_director_hash_index")]
[Index("ActivityHash", Name = "instances_activity_hash_index")]
[Index("Completed", Name = "instances_competed_index")]
[Index("CompletionReasons", Name = "instances_completion_reasons_index")]
[Index("CompletionReasons", "InstanceId", Name = "instances_completion_reasons_instance_id_index")]
[Index("InstanceId", "Completed", Name = "instances_instance_id_competed_index")]
[Index("InstanceId", Name = "instances_instance_id_index")]
[Index("InstanceId", "StartedFromBeginning", Name = "instances_instance_id_started_from_beginning_index")]
[Index("IsPrivate", Name = "instances_is_private_index")]
[Index("OccurredAt", Name = "instances_occurred_at_index")]
[Index("StartedFromBeginning", Name = "instances_started_from_beginning_index")]
[Index("StartingPhaseIndex", Name = "instances_starting_phase_index_index")]
public partial class Instance
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("instance_id")]
    public long InstanceId { get; set; }

    [Column("occurred_at")]
    public long OccurredAt { get; set; }

    [Column("starting_phase_index")]
    public int StartingPhaseIndex { get; set; }

    [Column("started_from_beginning")]
    public bool StartedFromBeginning { get; set; }

    [Column("activity_hash")]
    public uint ActivityHash { get; set; }

    [Column("activity_director_hash")]
    public uint ActivityDirectorHash { get; set; }

    [Column("is_private")]
    public bool IsPrivate { get; set; }

    [Column("completed")]
    public bool Completed { get; set; }

    [Required]
    [Column("completion_reasons")]
    public string CompletionReasons { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}