// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("manifest_triumphs")]
[Index("Hash", IsUnique = true)]
[Index("Gilded", Name = "manifest_triumphs_gilded_index")]
[Index("Hash", Name = "manifest_triumphs_hash_index")]
[Index("IsTitle", Name = "manifest_triumphs_is_title_index")]
[Index("Name", Name = "manifest_triumphs_name_index")]
[Index("Title", Name = "manifest_triumphs_title_index")]
public partial class ManifestTriumph
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("hash")]
    public uint Hash { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("description")]
    public string Description { get; set; }

    [Required]
    [Column("title")]
    public string Title { get; set; }

    [Column("is_title")]
    public bool IsTitle { get; set; }

    [Column("gilded")]
    public bool Gilded { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}