// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("manifest_seasons")]
[Index("Hash", IsUnique = true)]
[Index("Hash", Name = "manifest_seasons_hash_index")]
[Index("Name", Name = "manifest_seasons_name_index")]
[Index("Number", Name = "manifest_seasons_number_index")]
public partial class ManifestSeason
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("hash")]
    public uint Hash { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("pass_hash")]
    public uint PassHash { get; set; }

    [Column("number")]
    public int Number { get; set; }

    [Column("starts_at")]
    public long StartsAt { get; set; }

    [Column("ends_at")]
    public long EndsAt { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}