// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("manifest_activities")]
[Index("Hash", IsUnique = true)]
[Index("ActivityType", Name = "manifest_activities_activity_type_index")]
[Index("Hash", Name = "manifest_activities_hash_index")]
[Index("Index", Name = "manifest_activities_index_index")]
[Index("IsPvp", Name = "manifest_activities_is_pvp_index")]
[Index("MatchmakingEnabled", Name = "manifest_activities_matchmaking_enabled_index")]
[Index("Name", Name = "manifest_activities_name_index")]
public partial class ManifestActivity
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("activity_type")]
    public long ActivityType { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("description")]
    public string Description { get; set; }

    [Column("hash")]
    public uint Hash { get; set; }

    [Column("index")]
    public int Index { get; set; }

    [Column("is_pvp")]
    public bool IsPvp { get; set; }

    [Required]
    [Column("image_url")]
    public string ImageUrl { get; set; }

    [Column("matchmaking_enabled")]
    public bool MatchmakingEnabled { get; set; }

    [Column("fireteam_min_size")]
    public int FireteamMinSize { get; set; }

    [Column("fireteam_max_size")]
    public int FireteamMaxSize { get; set; }

    [Column("max_players")]
    public int MaxPlayers { get; set; }

    [Column("requires_guardian_oath")]
    public bool RequiresGuardianOath { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}