// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("manifest_activity_types")]
[Index("Hash", IsUnique = true)]
public partial class ManifestActivityType
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("hash")]
    public long Hash { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Required]
    [Column("description")]
    public string Description { get; set; }

    [Required]
    [Column("icon_url")]
    public string IconUrl { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }

    [Column("index")]
    public int Index { get; set; }
}