// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("member_triumphs")]
[Index("MembershipId", "Hash", IsUnique = true)]
[Index("Hash", Name = "member_triumphs_hash_index")]
[Index("MembershipId", Name = "member_triumphs_membership_id_index")]
[Index("State", Name = "member_triumphs_state_index")]
[Index("TimesCompleted", Name = "member_triumphs_times_completed_index")]
public partial class MemberTriumph
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("membership_id")]
    public long MembershipId { get; set; }

    [Column("hash")]
    public uint Hash { get; set; }

    [Column("state")]
    public int State { get; set; }

    [Column("times_completed")]
    public int TimesCompleted { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}