// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("member_activities")]
[Index("InstanceId", "MembershipId", "CharacterId", IsUnique = true)]
[Index("ActivityHashDirector", Name = "member_activities_activity_hash_director_index")]
[Index("ActivityHash", Name = "member_activities_activity_hash_index")]
[Index("CharacterId", Name = "member_activities_character_id_index")]
[Index("InstanceId", Name = "member_activities_instance_id_index")]
[Index("MembershipId", Name = "member_activities_membership_id_index")]
[Index("MembershipId", "InstanceId", Name = "member_activities_membership_id_instance_id_index")]
[Index("Mode", Name = "member_activities_mode_index")]
[Index("Modes", Name = "member_activities_modes_index")]
[Index("OccurredAt", Name = "member_activities_occurred_at_index")]
[Index("PlatformPlayed", Name = "member_activities_platform_played_index")]
[Index("Private", Name = "member_activities_private_index")]
public partial class MemberActivity
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("membership_id")]
    public long MembershipId { get; set; }

    [Column("character_id")]
    public long CharacterId { get; set; }

    [Column("platform_played")]
    public int PlatformPlayed { get; set; }

    [Column("activity_hash")]
    public uint ActivityHash { get; set; }

    [Column("activity_hash_director")]
    public uint ActivityHashDirector { get; set; }

    [Column("instance_id")]
    public long InstanceId { get; set; }

    [Column("mode")]
    public int Mode { get; set; }

    [Required]
    [Column("modes")]
    public string Modes { get; set; }

    [Column("private")]
    public bool Private { get; set; }

    [Column("occurred_at")]
    public long OccurredAt { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}