// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("member_activity_stats")]
[Index("MembershipId", "CharacterId", "InstanceId", "Name", IsUnique = true)]
[Index("CharacterId", Name = "member_activity_stats_character_id_index")]
[Index("InstanceId", Name = "member_activity_stats_instance_id_index")]
[Index("MembershipId", Name = "member_activity_stats_membership_id_index")]
[Index("MembershipId", "InstanceId", Name = "member_activity_stats_membership_id_instance_id_index")]
[Index("MembershipId", "InstanceId", "Name", Name = "member_activity_stats_membership_id_instance_id_name_index")]
[Index("Name", Name = "member_activity_stats_name_index")]
[Index("ValueDisplay", Name = "member_activity_stats_value_display_index")]
[Index("Value", Name = "member_activity_stats_value_index")]
public partial class MemberActivityStat
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("membership_id")]
    public long MembershipId { get; set; }

    [Column("character_id")]
    public long CharacterId { get; set; }

    [Column("instance_id")]
    public long InstanceId { get; set; }

    [Required]
    [Column("name")]
    public string Name { get; set; }

    [Column("value")]
    public double Value { get; set; }

    [Required]
    [Column("value_display")]
    public string ValueDisplay { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}