// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("member_characters")]
[Index("CharacterId", IsUnique = true)]
[Index("Platform", "MembershipId", "CharacterId", IsUnique = true)]
[Index("CharacterId", Name = "member_characters_character_id_index")]
[Index("ClassHash", Name = "member_characters_class_hash_index")]
[Index("EmblemBackgroundUrl", Name = "member_characters_emblem_background_url_index")]
[Index("EmblemHash", Name = "member_characters_emblem_hash_index")]
[Index("EmblemUrl", Name = "member_characters_emblem_url_index")]
[Index("MembershipId", Name = "member_characters_membership_id_index")]
[Index("Platform", Name = "member_characters_platform_index")]
public partial class MemberCharacter
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("membership_id")]
    public long MembershipId { get; set; }

    [Column("platform")]
    public int Platform { get; set; }

    [Column("character_id")]
    public long CharacterId { get; set; }

    [Column("class_hash")]
    public uint ClassHash { get; set; }

    [Column("light")]
    public int Light { get; set; }

    [Column("last_played_at")]
    public long LastPlayedAt { get; set; }

    [Column("minutes_played_session")]
    public long MinutesPlayedSession { get; set; }

    [Column("minutes_played_lifetime")]
    public long MinutesPlayedLifetime { get; set; }

    [Column("emblem_hash")]
    public uint EmblemHash { get; set; }

    [Required]
    [Column("emblem_url")]
    public string EmblemUrl { get; set; }

    [Required]
    [Column("emblem_background_url")]
    public string EmblemBackgroundUrl { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}