// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("members")]
[Index("MembershipId", IsUnique = true)]
[Index("DisplayNameGlobal", Name = "members_display_name_global_index")]
[Index("DisplayName", Name = "members_display_name_index")]
[Index("LastPlayedAt", Name = "members_last_played_at_index")]
[Index("Platform", Name = "members_platform_index")]
public partial class Member
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("membership_id")]
    public long MembershipId { get; set; }

    [Column("platform")]
    public int Platform { get; set; }

    [Required]
    [Column("display_name")]
    public string DisplayName { get; set; }

    [Required]
    [Column("display_name_global")]
    public string DisplayNameGlobal { get; set; }

    [Column("guardian_rank_current")]
    public int GuardianRankCurrent { get; set; }

    [Column("guardian_rank_lifetime")]
    public int GuardianRankLifetime { get; set; }

    [Column("last_played_at")]
    public long LastPlayedAt { get; set; }

    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}