// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Rasputin.Database.Models;

[Table("member_character_triumphs")]
[Index("MembershipId", "Hash", "CharacterId", IsUnique = true)]
[Index("Hash", Name = "member_character_triumphs_hash_index")]
[Index("MembershipId", Name = "member_character_triumphs_membership_id_index")]
[Index("CharacterId", Name = "member_character_triumphs_character_id_index")]
[Index("State", Name = "member_character_triumphs_state_index")]
public partial class MemberCharacterTriumph
{
    [Key]
    [Column("id")]
    public long Id { get; set; }

    [Column("membership_id")]
    public long MembershipId { get; set; }
    
    [Column("character_id")]
    public long CharacterId { get; set; }

    [Column("hash")]
    public uint Hash { get; set; }

    [Column("state")]
    public int State { get; set; }
    
    [Column("created_at")]
    public long CreatedAt { get; set; }

    [Column("updated_at")]
    public long UpdatedAt { get; set; }

    [Column("deleted_at")]
    public long DeletedAt { get; set; }
}