version: "3.8"
services:
  reverse-proxy:
    ports:
      - 80:80
      - 443:443
    image: nginx:1.22.1
    volumes:
      - ./certs:/etc/ssl/private
      - ./nginx-conf.d:/etc/nginx/conf.d
  database:
    ports:
      - 3306:3306
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD= yes